### ISSUE TITLE
Guild Window - Online Status Color

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI/ElvUI#109]
Shouldn't the status show Green when shown "Online" or "Offline" as white.

![wowscrnshot_012016_205219](https://cloud.githubusercontent.com/assets/7307335/12470400/6f22ec12-bfb9-11e5-8750-833e7f4e5195.jpg)

**Comment by Bunny67** [comment]
I do not understand what the problem :(

Google translates it is not clear

**Comment by Sylvictus** [comment]
He is saying that the class colours in the guild tab should not apply to the online/offline font status as well, I disagree entirely and recommend you delete this thread.

**Comment by crumdidlyumshis** [comment]
@Sylvictus Before you begin making orders, do a little research. I agree I am not fully correct on this matter, but I did happen to go on retail and check for myself. Maybe if you had as many bug reports as me you might have more say so. Fuck off.

![wowscrnshot_013116_103416](https://cloud.githubusercontent.com/assets/7307335/12703356/a5ff589c-c806-11e5-9d54-61aa5121b82d.jpg)

![wowscrnshot_013116_103408](https://cloud.githubusercontent.com/assets/7307335/12703357/aa163040-c806-11e5-8669-9864d507006d.jpg)

**Comment by Sylvictus** [comment]
Wow telling me the fuck off over this. Awesome I definitely respect your opinion now.

I don't really give a shit what retail has, first off, this is ElVUi for lich king.

Secondly this is not a bug report, at all. This is a slight annoyance that is ONLY ANNOYING TO YOU, and is aesthetic in nature. The online/offline in lich king ONLY shows up when you press the arrow over button and to code a specific portion of a file to where it turns either yellow or dimmed when you do is asinine and not worth his time anyway. Even if it wasn't a waste of time, it breaks the "flow" of things, it would feel abrupt for it to change colours just because you press the arrow over button. Which is why this is stupid. Once again this isn't retail.

**Comment by crumdidlyumshis** [comment]
Lol @Sylvictus 

Someone has a dirty tampon. FYI: http://www.webmd.com/women/guide/vaginal-douching-helpful-or-harmful

![you-mad-bro-](https://cloud.githubusercontent.com/assets/7307335/12705293/33384160-c834-11e5-92a3-eaddc965da8f.jpg)

But srsly gais. @Bunny67 Could you implement this? Thank you for your hard work!

**Comment by Sylvictus** [comment]
God damn you are so witty and mature. I almost feel like we could get past our squabbles and solve this problem if it wasn't for the fact that you are twelve and have no idea what a bug report is versus as aesthetic change that only you want that really is the developers choice anyway. The ELVUI in retail could easily keeps it class colours for the online text and you wouldn't have noticed or given two shits, you know why, because it fits that way too.

**Comment by crumdidlyumshis** [comment]
I'm not quite sure I understand your negative harassment. I guess I could say the same thing you just did? But why repeat what has been said. You get nowhere. If you're trying to make me mad or troll me, you're not doing a very good job at it. I find laughter at people like you. Whether I am twelve or sixty years of age, that is for you to believe. I just do what I can to help out Bunny67 by posting feedback or suggestions, issues, and what compares to how ElvUI should be. I don't care if it's retail or not. This addon was developed as a backported version of the retail ElvUI. He could have easily just taken the WotLK shitty version and worked off that. But no, Bunny67 decided to do what has not been done before; to create a near bug-free version of ElvUI made for WoD and used in WotLK. That my friend deserves a big round-of-applause. 

If you feel the need to help Bunny67, please do it in such a way that you are helping the community, not slandering. 

My 2 cents.

**Comment by crumdidlyumshis** [comment]
@Bunny67 Thank you again!

**Comment by Bunny67** [comment]
![wowscrnshot_020116_012635](https://cloud.githubusercontent.com/assets/5816685/12705430/e5965c9a-c882-11e5-9dbe-35c6c43cbf26.jpg)
So?

**Comment by crumdidlyumshis** [comment]
Beautiful! :) :+1:

**Comment by Nzith** [comment]
I think i will use the old ones...

**Comment by crumdidlyumshis** [comment]
Haha kk
