### ISSUE TITLE
Game Manu Access conflict with Addon Control Panel

### ISSUE THREAD

**Issue by Tiny6** [ElvUI/ElvUI#182]
![qq 20160812162950](https://cloud.githubusercontent.com/assets/16896017/17629554/79ece8fe-60aa-11e6-9152-da6fcc352a6a.png)

**Comment by Dissectional** [comment]
I'm still getting the problem highlighted here.
It displays correctly the first time I open the game menu but the second time I open the game menu it does not display correctly.

Is it accurate to report the problem here or open a new bug report?

![screenshot from 2016-08-17 19-37-24](https://cloud.githubusercontent.com/assets/3523233/17728562/e4e3443e-64b3-11e6-8e9c-d65280e383cc.jpeg)

**Comment by Bunny67** [comment]
check

**Comment by Dissectional** [comment]
Fixed :)

Thanks!
