### ISSUE TITLE
Chat incompatible with Guild2Guild

### ISSUE THREAD

**Issue by Icenova20** [ElvUI/ElvUI#69]
The relay isn't properly being hidden, like it is when using the add-on with Prat or classic chat.

What it currently looks like :
![wowscrnshot_101315_162846](https://cloud.githubusercontent.com/assets/15051986/10469011/f88c0168-71c7-11e5-80e6-8dc6cb25db9e.jpg)

It should only show the name of the person the message is being sent from and not the relay between the guilds.

Let me know if there is anymore information i can give to help resolve the issue.

G2G - http://wow.curseforge.com/addons/guild2guild/files/13-7-5-9/

**Comment by Bunny67** [comment]
I do not quite understand what the problem is. Installed add-on, do not understand how it works :( Bugs noticed :(

Ru: Не совсем понял в чем проблема. Установил аддон, не понял как он работает :( Багов не заметил :(

![wowscrnshot_101415_172859](https://cloud.githubusercontent.com/assets/5816685/10486849/8a6f534c-7299-11e5-8e80-df746881f42d.jpg)
